<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/audit_trail.php");
	include("$currDir/audit_trail_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('audit_trail');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "audit_trail";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`audit_trail`.`id`" => "id",
		"`audit_trail`.`username`" => "username",
		"`audit_trail`.`ip`" => "ip",
		"`audit_trail`.`ts`" => "ts",
		"`audit_trail`.`details`" => "details"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`audit_trail`.`id`',
		2 => 2,
		3 => 3,
		4 => '`audit_trail`.`ts`',
		5 => 5
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`audit_trail`.`id`" => "id",
		"`audit_trail`.`username`" => "username",
		"`audit_trail`.`ip`" => "ip",
		"`audit_trail`.`ts`" => "ts",
		"`audit_trail`.`details`" => "details"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`audit_trail`.`id`" => "ID",
		"`audit_trail`.`username`" => "Username",
		"`audit_trail`.`ip`" => "IP Address",
		"`audit_trail`.`ts`" => "Date/Time",
		"`audit_trail`.`details`" => "Details"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`audit_trail`.`id`" => "id",
		"`audit_trail`.`username`" => "username",
		"`audit_trail`.`ip`" => "ip",
		"`audit_trail`.`ts`" => "ts",
		"`audit_trail`.`details`" => "details"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`audit_trail` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "audit_trail_view.php";
	$x->RedirectAfterInsert = "audit_trail_view.php?SelectedID=#ID#";
	$x->TableTitle = "Audit Trail";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`audit_trail`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150);
	$x->ColCaption = array("Username", "IP Address", "Date/Time", "Details");
	$x->ColFieldName = array('username', 'ip', 'ts', 'details');
	$x->ColNumber  = array(2, 3, 4, 5);

	$x->Template = 'templates/audit_trail_templateTV.html';
	$x->SelectedTemplate = 'templates/audit_trail_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `audit_trail`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='audit_trail' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `audit_trail`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='audit_trail' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`audit_trail`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: audit_trail_init
	$render=TRUE;
	if(function_exists('audit_trail_init')){
		$args=array();
		$render=audit_trail_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: audit_trail_header
	$headerCode='';
	if(function_exists('audit_trail_header')){
		$args=array();
		$headerCode=audit_trail_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: audit_trail_footer
	$footerCode='';
	if(function_exists('audit_trail_footer')){
		$args=array();
		$footerCode=audit_trail_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>