<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

/*
	ajax-callable script that retrieves a list of users for admin, indicating which ones have
	access to supplied table.

	REQUEST parameters:
	===============
	t: table name
	id: optional, primary key value of current record
	p: page number (default = 1)
	s: search term
*/	

	/* return json */
	header('Content-type: application/json');

	$start_ts = microtime(true);

	$curr_dir=dirname(__FILE__);
	// include("$currDir/defaultLang.php");
	// include("$currDir/language.php");
	include("$currDir/lib.php");
	//require("{$curr_dir}/incCommon.php");

	$results_per_page = 50;

	$ids = false;
	if(isset($_REQUEST['ids']));{
		$ids = $_REQUEST['ids'];
		//print_r($_REQUEST['ids']);
	}
	if (isset($_REQUEST['table'])) {
		$table = $_REQUEST['table'];
		//print_r($_REQUEST['table']);
		//die;
	}

	/* a comma-separated list of IDs to use in the query */
	$cs_ids = '';
	foreach($ids as $id){
		$cs_ids .= "'" . makeSafe($id) . "',";
	}
	$cs_ids = substr($cs_ids, 0, -1); /* remove last comma */

	$items = array();
	$res = sql( "select * from {$table} " .
				"where id in ({$cs_ids})", $eo);
	while($row = db_fetch_assoc($res)){
		$items[] = $row;
		}

	//print_r($items);

	echo json_encode(array(
		'success' => true,
		'results' => $items,
		'elapsed' => round(microtime(true) - $start_ts, 3)
	));