<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	handle_maintenance();

	header("Content-type: text/javascript; charset=UTF-8");

	if(!get_sql_from('residence_and_rental_history')){ die('// Access denied!'); }

	$mfk=$_GET['mfk'];
	$id=makeSafe($_GET['id']);
	$rnd1=intval($_GET['rnd1']); if(!$rnd1) $rnd1='';

	if(!$mfk){
		die('// No js code available!');
	}

	switch($mfk){

		case 'tenant':
			if(!$id){
				?>
				$('monthly_rent<?php echo $rnd1; ?>').innerHTML='&nbsp;';
				$('security_deposit<?php echo $rnd1; ?>').innerHTML='&nbsp;';
				$('other_charges<?php echo $rnd1; ?>').innerHTML='&nbsp;';
				<?php
				break;
			}
			$res = sql("SELECT `applicants_and_tenants`.`id` as 'id', `applicants_and_tenants`.`last_name` as 'last_name', `applicants_and_tenants`.`first_name` as 'first_name', `applicants_and_tenants`.`email` as 'email', `applicants_and_tenants`.`phone` as 'phone', if(`applicants_and_tenants`.`birth_date`,date_format(`applicants_and_tenants`.`birth_date`,'%Y-%m-%d'),'') as 'birth_date', `applicants_and_tenants`.`status` as 'status', IF(    CHAR_LENGTH(`properties1`.`property_name`), CONCAT_WS('',   `properties1`.`property_name`), '') as 'property', IF(    CHAR_LENGTH(`properties2`.`property_name`) || CHAR_LENGTH(`units1`.`unit_number`), CONCAT_WS('',   `properties2`.`property_name`, ' - ', `units1`.`unit_number`), '') as 'unit', IF(    CHAR_LENGTH(`units1`.`rental_amount`), CONCAT_WS('',   `units1`.`rental_amount`), '') as 'monthly_rent', IF(    CHAR_LENGTH(`units1`.`deposit_amount`), CONCAT_WS('',   `units1`.`deposit_amount`), '') as 'security_deposit', IF(    CHAR_LENGTH(`units1`.`other_charges`), CONCAT_WS('',   `units1`.`other_charges`), '') as 'other_charges', `applicants_and_tenants`.`current_month_rent_status` as 'current_month_rent_status' FROM `applicants_and_tenants` LEFT JOIN `properties` as properties1 ON `properties1`.`id`=`applicants_and_tenants`.`property` LEFT JOIN `units` as units1 ON `units1`.`id`=`applicants_and_tenants`.`unit` LEFT JOIN `properties` as properties2 ON `properties2`.`id`=`units1`.`property`  WHERE `applicants_and_tenants`.`id`='$id' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#monthly_rent<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['monthly_rent']))); ?>&nbsp;');
			$j('#security_deposit<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['security_deposit']))); ?>&nbsp;');
			$j('#other_charges<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['other_charges']))); ?>&nbsp;');
			<?php
			break;


	}

?>