<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/residence_and_rental_history.php");
	include("$currDir/residence_and_rental_history_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('residence_and_rental_history');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "residence_and_rental_history";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`residence_and_rental_history`.`id`" => "id",
		"IF(    CHAR_LENGTH(`applicants_and_tenants1`.`first_name`) || CHAR_LENGTH(`applicants_and_tenants1`.`last_name`), CONCAT_WS('',   `applicants_and_tenants1`.`first_name`, ' ', `applicants_and_tenants1`.`last_name`), '') /* Tenant */" => "tenant",
		"if(`residence_and_rental_history`.`month`,date_format(`residence_and_rental_history`.`month`,'%m/%d/%Y'),'')" => "month",
		"IF(    CHAR_LENGTH(`units1`.`rental_amount`), CONCAT_WS('',   `units1`.`rental_amount`), '') /* Monthly rent */" => "monthly_rent",
		"IF(    CHAR_LENGTH(`units2`.`deposit_amount`), CONCAT_WS('',   `units2`.`deposit_amount`), '') /* Security Deposit */" => "security_deposit",
		"IF(    CHAR_LENGTH(`units3`.`other_charges`), CONCAT_WS('',   `units3`.`other_charges`), '') /* Other Charges */" => "other_charges",
		"`residence_and_rental_history`.`rent_paid`" => "rent_paid",
		"`residence_and_rental_history`.`rent_balance`" => "rent_balance",
		"if(`residence_and_rental_history`.`rent_reminder`,date_format(`residence_and_rental_history`.`rent_reminder`,'%m/%d/%Y'),'')" => "rent_reminder",
		"if(`residence_and_rental_history`.`due_date`,date_format(`residence_and_rental_history`.`due_date`,'%m/%d/%Y'),'')" => "due_date",
		"if(`residence_and_rental_history`.`late_rent_reminder`,date_format(`residence_and_rental_history`.`late_rent_reminder`,'%m/%d/%Y'),'')" => "late_rent_reminder",
		"`residence_and_rental_history`.`status`" => "status",
		"if(`residence_and_rental_history`.`duration_of_residency_from`,date_format(`residence_and_rental_history`.`duration_of_residency_from`,'%m/%d/%Y'),'')" => "duration_of_residency_from",
		"if(`residence_and_rental_history`.`to`,date_format(`residence_and_rental_history`.`to`,'%m/%d/%Y'),'')" => "to",
		"`residence_and_rental_history`.`reason_for_leaving`" => "reason_for_leaving",
		"`residence_and_rental_history`.`notes`" => "notes"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`residence_and_rental_history`.`id`',
		2 => 2,
		3 => '`residence_and_rental_history`.`month`',
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`residence_and_rental_history`.`rent_paid`',
		8 => '`residence_and_rental_history`.`rent_balance`',
		9 => '`residence_and_rental_history`.`rent_reminder`',
		10 => '`residence_and_rental_history`.`due_date`',
		11 => '`residence_and_rental_history`.`late_rent_reminder`',
		12 => 12,
		13 => '`residence_and_rental_history`.`duration_of_residency_from`',
		14 => '`residence_and_rental_history`.`to`',
		15 => 15,
		16 => 16
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`residence_and_rental_history`.`id`" => "id",
		"IF(    CHAR_LENGTH(`applicants_and_tenants1`.`first_name`) || CHAR_LENGTH(`applicants_and_tenants1`.`last_name`), CONCAT_WS('',   `applicants_and_tenants1`.`first_name`, ' ', `applicants_and_tenants1`.`last_name`), '') /* Tenant */" => "tenant",
		"if(`residence_and_rental_history`.`month`,date_format(`residence_and_rental_history`.`month`,'%m/%d/%Y'),'')" => "month",
		"IF(    CHAR_LENGTH(`units1`.`rental_amount`), CONCAT_WS('',   `units1`.`rental_amount`), '') /* Monthly rent */" => "monthly_rent",
		"IF(    CHAR_LENGTH(`units2`.`deposit_amount`), CONCAT_WS('',   `units2`.`deposit_amount`), '') /* Security Deposit */" => "security_deposit",
		"IF(    CHAR_LENGTH(`units3`.`other_charges`), CONCAT_WS('',   `units3`.`other_charges`), '') /* Other Charges */" => "other_charges",
		"`residence_and_rental_history`.`rent_paid`" => "rent_paid",
		"`residence_and_rental_history`.`rent_balance`" => "rent_balance",
		"if(`residence_and_rental_history`.`rent_reminder`,date_format(`residence_and_rental_history`.`rent_reminder`,'%m/%d/%Y'),'')" => "rent_reminder",
		"if(`residence_and_rental_history`.`due_date`,date_format(`residence_and_rental_history`.`due_date`,'%m/%d/%Y'),'')" => "due_date",
		"if(`residence_and_rental_history`.`late_rent_reminder`,date_format(`residence_and_rental_history`.`late_rent_reminder`,'%m/%d/%Y'),'')" => "late_rent_reminder",
		"`residence_and_rental_history`.`status`" => "status",
		"if(`residence_and_rental_history`.`duration_of_residency_from`,date_format(`residence_and_rental_history`.`duration_of_residency_from`,'%m/%d/%Y'),'')" => "duration_of_residency_from",
		"if(`residence_and_rental_history`.`to`,date_format(`residence_and_rental_history`.`to`,'%m/%d/%Y'),'')" => "to",
		"`residence_and_rental_history`.`reason_for_leaving`" => "reason_for_leaving",
		"`residence_and_rental_history`.`notes`" => "notes"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`residence_and_rental_history`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`applicants_and_tenants1`.`first_name`) || CHAR_LENGTH(`applicants_and_tenants1`.`last_name`), CONCAT_WS('',   `applicants_and_tenants1`.`first_name`, ' ', `applicants_and_tenants1`.`last_name`), '') /* Tenant */" => "Tenant",
		"`residence_and_rental_history`.`month`" => "Month",
		"IF(    CHAR_LENGTH(`units1`.`rental_amount`), CONCAT_WS('',   `units1`.`rental_amount`), '') /* Monthly rent */" => "Monthly rent",
		"IF(    CHAR_LENGTH(`units2`.`deposit_amount`), CONCAT_WS('',   `units2`.`deposit_amount`), '') /* Security Deposit */" => "Security Deposit",
		"IF(    CHAR_LENGTH(`units3`.`other_charges`), CONCAT_WS('',   `units3`.`other_charges`), '') /* Other Charges */" => "Other Charges",
		"`residence_and_rental_history`.`rent_paid`" => "Rent Paid",
		"`residence_and_rental_history`.`rent_balance`" => "Rent Balance",
		"`residence_and_rental_history`.`rent_reminder`" => "Rent Reminder Date",
		"`residence_and_rental_history`.`due_date`" => "Due date",
		"`residence_and_rental_history`.`late_rent_reminder`" => "Late Rent Reminder Date",
		"`residence_and_rental_history`.`status`" => "Status",
		"`residence_and_rental_history`.`duration_of_residency_from`" => "Duration of residency from",
		"`residence_and_rental_history`.`to`" => "to",
		"`residence_and_rental_history`.`reason_for_leaving`" => "Reason for leaving",
		"`residence_and_rental_history`.`notes`" => "Notes"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`residence_and_rental_history`.`id`" => "id",
		"IF(    CHAR_LENGTH(`applicants_and_tenants1`.`first_name`) || CHAR_LENGTH(`applicants_and_tenants1`.`last_name`), CONCAT_WS('',   `applicants_and_tenants1`.`first_name`, ' ', `applicants_and_tenants1`.`last_name`), '') /* Tenant */" => "tenant",
		"if(`residence_and_rental_history`.`month`,date_format(`residence_and_rental_history`.`month`,'%m/%d/%Y'),'')" => "month",
		"IF(    CHAR_LENGTH(`units1`.`rental_amount`), CONCAT_WS('',   `units1`.`rental_amount`), '') /* Monthly rent */" => "monthly_rent",
		"IF(    CHAR_LENGTH(`units2`.`deposit_amount`), CONCAT_WS('',   `units2`.`deposit_amount`), '') /* Security Deposit */" => "security_deposit",
		"IF(    CHAR_LENGTH(`units3`.`other_charges`), CONCAT_WS('',   `units3`.`other_charges`), '') /* Other Charges */" => "other_charges",
		"`residence_and_rental_history`.`rent_paid`" => "rent_paid",
		"`residence_and_rental_history`.`rent_balance`" => "rent_balance",
		"if(`residence_and_rental_history`.`rent_reminder`,date_format(`residence_and_rental_history`.`rent_reminder`,'%m/%d/%Y'),'')" => "rent_reminder",
		"if(`residence_and_rental_history`.`due_date`,date_format(`residence_and_rental_history`.`due_date`,'%m/%d/%Y'),'')" => "due_date",
		"if(`residence_and_rental_history`.`late_rent_reminder`,date_format(`residence_and_rental_history`.`late_rent_reminder`,'%m/%d/%Y'),'')" => "late_rent_reminder",
		"`residence_and_rental_history`.`status`" => "status",
		"if(`residence_and_rental_history`.`duration_of_residency_from`,date_format(`residence_and_rental_history`.`duration_of_residency_from`,'%m/%d/%Y'),'')" => "duration_of_residency_from",
		"if(`residence_and_rental_history`.`to`,date_format(`residence_and_rental_history`.`to`,'%m/%d/%Y'),'')" => "to",
		"`residence_and_rental_history`.`reason_for_leaving`" => "reason_for_leaving",
		"`residence_and_rental_history`.`notes`" => "notes"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'tenant' => 'Tenant', 'monthly_rent' => 'Monthly rent', 'security_deposit' => 'Security Deposit', 'other_charges' => 'Other Charges');

	$x->QueryFrom="`residence_and_rental_history` LEFT JOIN `applicants_and_tenants` as applicants_and_tenants1 ON `applicants_and_tenants1`.`id`=`residence_and_rental_history`.`tenant` LEFT JOIN `applicants_and_tenants` as applicants_and_tenants2 ON `applicants_and_tenants2`.`id`=`residence_and_rental_history`.`monthly_rent` LEFT JOIN `units` as units1 ON `units1`.`id`=`applicants_and_tenants2`.`monthly_rent` LEFT JOIN `applicants_and_tenants` as applicants_and_tenants3 ON `applicants_and_tenants3`.`id`=`residence_and_rental_history`.`security_deposit` LEFT JOIN `units` as units2 ON `units2`.`id`=`applicants_and_tenants3`.`security_deposit` LEFT JOIN `applicants_and_tenants` as applicants_and_tenants4 ON `applicants_and_tenants4`.`id`=`residence_and_rental_history`.`other_charges` LEFT JOIN `units` as units3 ON `units3`.`id`=`applicants_and_tenants4`.`other_charges` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "residence_and_rental_history_view.php";
	$x->RedirectAfterInsert = "residence_and_rental_history_view.php?SelectedID=#ID#";
	$x->TableTitle = "Rental history";
	$x->TableIcon = "resources/table_icons/document_comment_above.png";
	$x->PrimaryKey = "`residence_and_rental_history`.`id`";

	$x->ColWidth   = array(  100, 80, 80, 150, 80, 80, 100, 100, 100, 150, 100, 80, 120);
	$x->ColCaption = array("Month", "Monthly rent", "Security Deposit", "Other Charges", "Rent Paid", "Rent Balance", "Rent Reminder Date", "Due date", "Late Rent Reminder Date", "Status", "Duration of residency from", "to", "Reason for leaving");
	$x->ColFieldName = array('month', 'monthly_rent', 'security_deposit', 'other_charges', 'rent_paid', 'rent_balance', 'rent_reminder', 'due_date', 'late_rent_reminder', 'status', 'duration_of_residency_from', 'to', 'reason_for_leaving');
	$x->ColNumber  = array(3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);

	$x->Template = 'templates/residence_and_rental_history_templateTV.html';
	$x->SelectedTemplate = 'templates/residence_and_rental_history_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `residence_and_rental_history`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='residence_and_rental_history' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `residence_and_rental_history`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='residence_and_rental_history' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`residence_and_rental_history`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: residence_and_rental_history_init
	$render=TRUE;
	if(function_exists('residence_and_rental_history_init')){
		$args=array();
		$render=residence_and_rental_history_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: residence_and_rental_history_header
	$headerCode='';
	if(function_exists('residence_and_rental_history_header')){
		$args=array();
		$headerCode=residence_and_rental_history_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: residence_and_rental_history_footer
	$footerCode='';
	if(function_exists('residence_and_rental_history_footer')){
		$args=array();
		$footerCode=residence_and_rental_history_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>