<?php
// This script and data application were generated by AppGini 5.51
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/tenant_unit_rent.php");
	include("$currDir/tenant_unit_rent_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('tenant_unit_rent');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "tenant_unit_rent";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`tenant_unit_rent`.`id`" => "id",
		"IF(    CHAR_LENGTH(`units1`.`id`), CONCAT_WS('',   `units1`.`id`), '') /* Unit */" => "unit",
		"IF(    CHAR_LENGTH(`units2`.`rental_amount`), CONCAT_WS('',   `units2`.`rental_amount`), '') /* Monthly rent */" => "monthly_rent",
		"IF(    CHAR_LENGTH(`applicants_and_tenants1`.`last_name`), CONCAT_WS('',   `applicants_and_tenants1`.`last_name`), '') /* Tenant */" => "tenant"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`tenant_unit_rent`.`id`',
		2 => 2,
		3 => 3,
		4 => 4
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`tenant_unit_rent`.`id`" => "id",
		"IF(    CHAR_LENGTH(`units1`.`id`), CONCAT_WS('',   `units1`.`id`), '') /* Unit */" => "unit",
		"IF(    CHAR_LENGTH(`units2`.`rental_amount`), CONCAT_WS('',   `units2`.`rental_amount`), '') /* Monthly rent */" => "monthly_rent",
		"IF(    CHAR_LENGTH(`applicants_and_tenants1`.`last_name`), CONCAT_WS('',   `applicants_and_tenants1`.`last_name`), '') /* Tenant */" => "tenant"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`tenant_unit_rent`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`units1`.`id`), CONCAT_WS('',   `units1`.`id`), '') /* Unit */" => "Unit",
		"IF(    CHAR_LENGTH(`units2`.`rental_amount`), CONCAT_WS('',   `units2`.`rental_amount`), '') /* Monthly rent */" => "Monthly rent",
		"IF(    CHAR_LENGTH(`applicants_and_tenants1`.`last_name`), CONCAT_WS('',   `applicants_and_tenants1`.`last_name`), '') /* Tenant */" => "Tenant"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`tenant_unit_rent`.`id`" => "id",
		"IF(    CHAR_LENGTH(`units1`.`id`), CONCAT_WS('',   `units1`.`id`), '') /* Unit */" => "unit",
		"IF(    CHAR_LENGTH(`units2`.`rental_amount`), CONCAT_WS('',   `units2`.`rental_amount`), '') /* Monthly rent */" => "monthly_rent",
		"IF(    CHAR_LENGTH(`applicants_and_tenants1`.`last_name`), CONCAT_WS('',   `applicants_and_tenants1`.`last_name`), '') /* Tenant */" => "tenant"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'unit' => 'Unit', 'monthly_rent' => 'Monthly rent', 'tenant' => 'Tenant');

	$x->QueryFrom="`tenant_unit_rent` LEFT JOIN `units` as units1 ON `units1`.`id`=`tenant_unit_rent`.`unit` LEFT JOIN `units` as units2 ON `units2`.`id`=`tenant_unit_rent`.`monthly_rent` LEFT JOIN `applicants_and_tenants` as applicants_and_tenants1 ON `applicants_and_tenants1`.`id`=`tenant_unit_rent`.`tenant` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "tenant_unit_rent_view.php";
	$x->RedirectAfterInsert = "tenant_unit_rent_view.php?SelectedID=#ID#";
	$x->TableTitle = "Tenant unit rent";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`tenant_unit_rent`.`id`";

	$x->ColWidth   = array(  150, 150, 150);
	$x->ColCaption = array("Unit", "Monthly rent", "Tenant");
	$x->ColFieldName = array('unit', 'monthly_rent', 'tenant');
	$x->ColNumber  = array(2, 3, 4);

	$x->Template = 'templates/tenant_unit_rent_templateTV.html';
	$x->SelectedTemplate = 'templates/tenant_unit_rent_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tenant_unit_rent`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='tenant_unit_rent' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tenant_unit_rent`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='tenant_unit_rent' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`tenant_unit_rent`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: tenant_unit_rent_init
	$render=TRUE;
	if(function_exists('tenant_unit_rent_init')){
		$args=array();
		$render=tenant_unit_rent_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tenant_unit_rent_header
	$headerCode='';
	if(function_exists('tenant_unit_rent_header')){
		$args=array();
		$headerCode=tenant_unit_rent_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: tenant_unit_rent_footer
	$footerCode='';
	if(function_exists('tenant_unit_rent_footer')){
		$args=array();
		$footerCode=tenant_unit_rent_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>